services:
  node-app:
    build:
      dockerfile: Dockerfile
    ports: 
      - 5000:5000
    command: npm run dev
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - PORT=5000
      - DB_USERNAME=nikola
      - DB_PASSWORD=CEIkRyxQ3ThMRxPh
      - SECRET_KEY=my-secret-key
      - CERTIFICATE_PATH=config/ssh/certificate.pem
      - PRIVATE_KEY=config/ssh/private-key.pem