name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx (optional, but useful for advanced Docker features)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build Docker image using Docker Compose
      - name: Build Docker image with Docker Compose
        run: |
          # Ensure you're in the root directory of the repo
          cd $GITHUB_WORKSPACE  # Make sure to change directory to the root of the repo
          docker compose -f docker-compose.yaml build

      # Step 5: Push Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker compose -f docker-compose.yaml push
