# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
  
      # Step 2: Set up Docker and Docker Compose (if not pre-installed)
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
  
      - name: Set up Docker Compose
        run: sudo apt-get install docker-compose
  
      # Step 3: Log in to Docker Hub (using secrets for credentials)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
  
      # Step 4: Build the images using Docker Compose
      - name: Build Docker Images with Docker Compose
        run: |
          docker-compose -f docker-compose.yaml build
  
      # Step 5: Push Docker Images using Docker Compose
      - name: Push Docker Images to Docker Hub
        run: |
          docker-compose -f docker-compose.yaml push
  
      # Optional: Step 6 - Verify that the image was built and pushed
      - name: List Docker images
        run: docker images

